/**
 * @deprecated Use tools-storage.ts instead for hybrid storage support
 * This file is kept for backward compatibility but redirects to tools-storage
 */

// Re-export all functions from tools-storage for backward compatibility
export {
  saveClient,
  getClients,
  getClientById,
  deleteClient,
  saveInvoice,
  getInvoices,
  getInvoiceById,
  deleteInvoice,
  getNextInvoiceNumber,
  incrementInvoiceNumber,
  getSettings,
  saveSettings,
  saveQuotation,
  getQuotations,
  getQuotationById,
  deleteQuotation,
  saveReceipt,
  getReceipts,
  getReceiptById,
  deleteReceipt,
  getNextReceiptNumber,
  saveContract,
  getContracts,
  getContractById,
  deleteContract,
  getNextContractNumber,
  saveTimeEntry,
  getTimeEntries,
  getTimeEntryById,
  deleteTimeEntry,
  getInvoiceStats,
  getReceiptStats,
  getContractStats,
  saveResume,
  getResumes,
  getResumeById,
  deleteResume,
  duplicateResume,
  getResumeStats,
  exportResumeJSON,
  importResumeJSON,
  exportAllData,
  importAllData,
} from "@/lib/storage/tools-storage"
