import type { Template } from "./types"

export const defaultPresetKey = "ecommerce"

export const templates: Record<string, Template> = {
  ecommerce: {
    label: "E-Commerce",
    note: "Product catalog, cart, orders, and admin management.",
    defaultPackage: "mvp",
    features: [
      {
        id: "flutter_core",
        name: "Flutter app core",
        scope: "App shell, navigation, theming",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "product_catalog",
        name: "Product catalog",
        scope: "Categories, list, detail",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "product_variants",
        name: "Product variants",
        scope: "Size, color, attributes",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "search_filters",
        name: "Search + filters",
        scope: "Keyword + multi-filter",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "cart",
        name: "Cart",
        scope: "Add, update, totals",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "checkout",
        name: "Checkout (no payment)",
        scope: "Address, delivery, confirm",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "order_history",
        name: "Order history",
        scope: "List + detail view",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "order_tracking",
        name: "Order tracking",
        scope: "Status timeline",
        daysLow: 2,
        daysHigh: 3,
        selected: false,
      },
      {
        id: "notifications",
        name: "Notifications",
        scope: "Push or SMS trigger",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "localization",
        name: "Localization",
        scope: "Burmese + English",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_auth",
        name: "Admin auth",
        scope: "Roles and permissions",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "admin_product_mgmt",
        name: "Admin product mgmt",
        scope: "CRUD + images",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "admin_inventory",
        name: "Admin inventory",
        scope: "Stock updates",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_order_mgmt",
        name: "Admin order mgmt",
        scope: "Status workflow",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "admin_reports",
        name: "Admin reports",
        scope: "Basic stats + export",
        daysLow: 3,
        daysHigh: 6,
        selected: false,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, catalog, orders APIs",
        daysLow: 8,
        daysHigh: 14,
        selected: true,
      },
      {
        id: "file_storage",
        name: "File storage",
        scope: "Image upload + CDN",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
    ],
    packages: {
      mvp: [
        "flutter_core",
        "product_catalog",
        "product_variants",
        "cart",
        "checkout",
        "order_history",
        "admin_auth",
        "admin_product_mgmt",
        "admin_order_mgmt",
        "backend_core",
        "file_storage",
      ],
      standard: [
        "flutter_core",
        "product_catalog",
        "product_variants",
        "search_filters",
        "cart",
        "checkout",
        "order_history",
        "order_tracking",
        "notifications",
        "admin_auth",
        "admin_product_mgmt",
        "admin_order_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
      advanced: [
        "flutter_core",
        "product_catalog",
        "product_variants",
        "search_filters",
        "cart",
        "checkout",
        "order_history",
        "order_tracking",
        "notifications",
        "localization",
        "admin_auth",
        "admin_product_mgmt",
        "admin_inventory",
        "admin_order_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
    },
  },
  booking: {
    label: "Service Booking",
    note: "Appointments, availability, and booking management.",
    defaultPackage: "mvp",
    features: [
      {
        id: "flutter_core",
        name: "Flutter app core",
        scope: "App shell, navigation, theming",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "service_catalog",
        name: "Service catalog",
        scope: "Services, pricing, detail view",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "provider_profiles",
        name: "Provider profiles",
        scope: "Staff profiles, bios, skills",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "availability",
        name: "Availability calendar",
        scope: "Slots, availability rules",
        daysLow: 3,
        daysHigh: 6,
        selected: false,
      },
      {
        id: "booking_flow",
        name: "Booking flow",
        scope: "Select, confirm, manage",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "reschedule",
        name: "Reschedule & cancel",
        scope: "Reschedule rules, cancellations",
        daysLow: 2,
        daysHigh: 3,
        selected: false,
      },
      {
        id: "notifications",
        name: "Notifications",
        scope: "Push or SMS trigger",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "location_map",
        name: "Location map",
        scope: "Map view + location details",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "reviews",
        name: "Reviews & ratings",
        scope: "User reviews and stars",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "localization",
        name: "Localization",
        scope: "Burmese + English",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_auth",
        name: "Admin auth",
        scope: "Roles and permissions",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "admin_service_mgmt",
        name: "Admin service mgmt",
        scope: "CRUD for services",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "admin_booking_mgmt",
        name: "Admin booking mgmt",
        scope: "Manage bookings and status",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "admin_reports",
        name: "Admin reports",
        scope: "Basic stats + export",
        daysLow: 3,
        daysHigh: 6,
        selected: false,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, booking APIs",
        daysLow: 8,
        daysHigh: 14,
        selected: true,
      },
      {
        id: "file_storage",
        name: "File storage",
        scope: "Image upload + CDN",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
    ],
    packages: {
      mvp: [
        "flutter_core",
        "service_catalog",
        "booking_flow",
        "admin_auth",
        "admin_service_mgmt",
        "admin_booking_mgmt",
        "backend_core",
        "file_storage",
      ],
      standard: [
        "flutter_core",
        "service_catalog",
        "availability",
        "booking_flow",
        "notifications",
        "location_map",
        "admin_auth",
        "admin_service_mgmt",
        "admin_booking_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
      advanced: [
        "flutter_core",
        "service_catalog",
        "provider_profiles",
        "availability",
        "booking_flow",
        "reschedule",
        "notifications",
        "location_map",
        "reviews",
        "localization",
        "admin_auth",
        "admin_service_mgmt",
        "admin_booking_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
    },
  },
  marketplace: {
    label: "Marketplace",
    note: "Multi-vendor listings, vendor tools, and commission rules.",
    defaultPackage: "mvp",
    features: [
      {
        id: "flutter_core",
        name: "Flutter app core",
        scope: "App shell, navigation, theming",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "product_catalog",
        name: "Listings catalog",
        scope: "Categories, list, detail",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "vendor_onboarding",
        name: "Vendor onboarding",
        scope: "Signup, verification flow",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "vendor_dashboard",
        name: "Vendor dashboard",
        scope: "Manage listings + orders",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "commission_rules",
        name: "Commission rules",
        scope: "Fee rules + calculations",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "search_filters",
        name: "Search + filters",
        scope: "Keyword + multi-filter",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "cart",
        name: "Cart",
        scope: "Add, update, totals",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "checkout",
        name: "Checkout (no payment)",
        scope: "Address, delivery, confirm",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "order_history",
        name: "Order history",
        scope: "List + detail view",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "notifications",
        name: "Notifications",
        scope: "Push or SMS trigger",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "localization",
        name: "Localization",
        scope: "Burmese + English",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_auth",
        name: "Admin auth",
        scope: "Roles and permissions",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "admin_vendor_mgmt",
        name: "Admin vendor mgmt",
        scope: "Vendors, approvals",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "admin_order_mgmt",
        name: "Admin order mgmt",
        scope: "Status workflow",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "admin_reports",
        name: "Admin reports",
        scope: "Basic stats + export",
        daysLow: 3,
        daysHigh: 6,
        selected: false,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, listings, orders APIs",
        daysLow: 8,
        daysHigh: 14,
        selected: true,
      },
      {
        id: "file_storage",
        name: "File storage",
        scope: "Image upload + CDN",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
    ],
    packages: {
      mvp: [
        "flutter_core",
        "product_catalog",
        "vendor_onboarding",
        "vendor_dashboard",
        "cart",
        "checkout",
        "order_history",
        "admin_auth",
        "admin_vendor_mgmt",
        "admin_order_mgmt",
        "backend_core",
        "file_storage",
      ],
      standard: [
        "flutter_core",
        "product_catalog",
        "vendor_onboarding",
        "vendor_dashboard",
        "search_filters",
        "cart",
        "checkout",
        "order_history",
        "notifications",
        "admin_auth",
        "admin_vendor_mgmt",
        "admin_order_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
      advanced: [
        "flutter_core",
        "product_catalog",
        "vendor_onboarding",
        "vendor_dashboard",
        "commission_rules",
        "search_filters",
        "cart",
        "checkout",
        "order_history",
        "notifications",
        "localization",
        "admin_auth",
        "admin_vendor_mgmt",
        "admin_order_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
    },
  },
  pos: {
    label: "POS / Retail",
    note: "Point-of-sale, staff access, inventory, and receipts.",
    defaultPackage: "mvp",
    features: [
      {
        id: "pos_core",
        name: "POS app core",
        scope: "Quick navigation, cashier flow",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "product_catalog",
        name: "Product catalog",
        scope: "Categories, barcode list",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "barcode_scan",
        name: "Barcode scanning",
        scope: "Camera scan + lookup",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "cart",
        name: "Cart & checkout",
        scope: "Totals, discounts, notes",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "receipt_printing",
        name: "Receipt printing",
        scope: "Bluetooth / PDF receipts",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "staff_roles",
        name: "Staff roles",
        scope: "Cashier, manager access",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "inventory",
        name: "Inventory tracking",
        scope: "Stock adjustments, alerts",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "shift_reports",
        name: "Shift reports",
        scope: "Daily sales summary",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_dashboard",
        name: "Admin dashboard",
        scope: "Products, staff, reports",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, inventory, sales APIs",
        daysLow: 6,
        daysHigh: 10,
        selected: true,
      },
    ],
    packages: {
      mvp: [
        "pos_core",
        "product_catalog",
        "barcode_scan",
        "cart",
        "inventory",
        "admin_dashboard",
        "backend_core",
      ],
      standard: [
        "pos_core",
        "product_catalog",
        "barcode_scan",
        "cart",
        "receipt_printing",
        "inventory",
        "shift_reports",
        "admin_dashboard",
        "backend_core",
      ],
      advanced: [
        "pos_core",
        "product_catalog",
        "barcode_scan",
        "cart",
        "receipt_printing",
        "staff_roles",
        "inventory",
        "shift_reports",
        "admin_dashboard",
        "backend_core",
      ],
    },
  },
  crm: {
    label: "CRM",
    note: "Leads, pipeline, customer tracking, and sales reports.",
    defaultPackage: "mvp",
    features: [
      {
        id: "crm_core",
        name: "CRM core",
        scope: "Pipeline, stages, boards",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "contacts",
        name: "Contacts",
        scope: "Companies, people, notes",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "lead_capture",
        name: "Lead capture",
        scope: "Forms + lead intake",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "tasks",
        name: "Tasks & reminders",
        scope: "To-dos, reminders",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "email_logs",
        name: "Communication logs",
        scope: "Emails, calls, notes",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "reports",
        name: "Sales reports",
        scope: "Pipeline + conversion",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "admin_dashboard",
        name: "Admin dashboard",
        scope: "Users, pipelines, settings",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, CRM APIs",
        daysLow: 6,
        daysHigh: 10,
        selected: true,
      },
    ],
    packages: {
      mvp: ["crm_core", "contacts", "reports", "admin_dashboard", "backend_core"],
      standard: [
        "crm_core",
        "contacts",
        "lead_capture",
        "tasks",
        "reports",
        "admin_dashboard",
        "backend_core",
      ],
      advanced: [
        "crm_core",
        "contacts",
        "lead_capture",
        "tasks",
        "email_logs",
        "reports",
        "admin_dashboard",
        "backend_core",
      ],
    },
  },
  lms: {
    label: "LMS",
    note: "Courses, lessons, student progress, and admin publishing.",
    defaultPackage: "mvp",
    features: [
      {
        id: "lms_core",
        name: "LMS core",
        scope: "Course catalog, enrollment",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "lesson_player",
        name: "Lesson player",
        scope: "Video, text, resources",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "quizzes",
        name: "Quizzes",
        scope: "Questions, scoring",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "assignments",
        name: "Assignments",
        scope: "Submissions, grading",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "progress_tracking",
        name: "Progress tracking",
        scope: "Completion stats",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "certificates",
        name: "Certificates",
        scope: "Certificate issuance",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_course_mgmt",
        name: "Admin course mgmt",
        scope: "Create, publish, manage",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "admin_reports",
        name: "Admin reports",
        scope: "Student analytics",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, LMS APIs",
        daysLow: 6,
        daysHigh: 10,
        selected: true,
      },
    ],
    packages: {
      mvp: [
        "lms_core",
        "lesson_player",
        "progress_tracking",
        "admin_course_mgmt",
        "backend_core",
      ],
      standard: [
        "lms_core",
        "lesson_player",
        "quizzes",
        "progress_tracking",
        "admin_course_mgmt",
        "admin_reports",
        "backend_core",
      ],
      advanced: [
        "lms_core",
        "lesson_player",
        "quizzes",
        "assignments",
        "progress_tracking",
        "certificates",
        "admin_course_mgmt",
        "admin_reports",
        "backend_core",
      ],
    },
  },
  content: {
    label: "Content / Media",
    note: "Articles, media libraries, and content management.",
    defaultPackage: "mvp",
    features: [
      {
        id: "flutter_core",
        name: "Flutter app core",
        scope: "App shell, navigation, theming",
        daysLow: 3,
        daysHigh: 5,
        selected: true,
      },
      {
        id: "content_catalog",
        name: "Content catalog",
        scope: "List, detail, categories",
        daysLow: 3,
        daysHigh: 6,
        selected: true,
      },
      {
        id: "categories_tags",
        name: "Categories + tags",
        scope: "Taxonomy management",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "search_filters",
        name: "Search + filters",
        scope: "Keyword + multi-filter",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "bookmarks",
        name: "Bookmarks",
        scope: "Save and revisit content",
        daysLow: 2,
        daysHigh: 3,
        selected: false,
      },
      {
        id: "offline_reading",
        name: "Offline reading",
        scope: "Download + cache",
        daysLow: 3,
        daysHigh: 5,
        selected: false,
      },
      {
        id: "notifications",
        name: "Notifications",
        scope: "Push updates",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "localization",
        name: "Localization",
        scope: "Burmese + English",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "admin_auth",
        name: "Admin auth",
        scope: "Roles and permissions",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
      {
        id: "admin_content_mgmt",
        name: "Admin content mgmt",
        scope: "CRUD + publishing",
        daysLow: 4,
        daysHigh: 7,
        selected: true,
      },
      {
        id: "admin_reports",
        name: "Admin reports",
        scope: "Basic stats + export",
        daysLow: 2,
        daysHigh: 4,
        selected: false,
      },
      {
        id: "backend_core",
        name: "Backend core",
        scope: "Auth, content APIs",
        daysLow: 6,
        daysHigh: 10,
        selected: true,
      },
      {
        id: "file_storage",
        name: "File storage",
        scope: "Media upload + CDN",
        daysLow: 2,
        daysHigh: 4,
        selected: true,
      },
    ],
    packages: {
      mvp: [
        "flutter_core",
        "content_catalog",
        "categories_tags",
        "admin_auth",
        "admin_content_mgmt",
        "backend_core",
        "file_storage",
      ],
      standard: [
        "flutter_core",
        "content_catalog",
        "categories_tags",
        "search_filters",
        "bookmarks",
        "notifications",
        "admin_auth",
        "admin_content_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
      advanced: [
        "flutter_core",
        "content_catalog",
        "categories_tags",
        "search_filters",
        "bookmarks",
        "offline_reading",
        "notifications",
        "localization",
        "admin_auth",
        "admin_content_mgmt",
        "admin_reports",
        "backend_core",
        "file_storage",
      ],
    },
  },
  custom: {
    label: "Custom (empty)",
    note: "Start from scratch and add your own features.",
    defaultPackage: "mvp",
    features: [],
    packages: {
      mvp: [],
      standard: [],
      advanced: [],
    },
  },
}

export const presetOrder = [
  "ecommerce",
  "booking",
  "marketplace",
  "pos",
  "crm",
  "lms",
  "content",
  "custom",
]
